# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Irene Ibáñez Martínez
title: Frontend Developer (Angular)
email: irene.ibanez.dev@gmail.com
website: https://ireneibanez.github.io/cv/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  ireneibanez
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: irene-ibanez-martinez
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mí
about_profile_image: images/Ire.jpg
about_content: | # this will include new lines to allow paragraphs
  Soy ambientóloga, científica marina y desarrolladora web. Me encantaría encontrar un reto interesante que aunara mis dos pasiones, el medio ambiente y la sostenibilidad y el desarrollo web.

  La mayoría de mis conocimientos y experiencia giran en torno al frontend: <mark>Typescript/Javascript</mark>, <mark>Angular</mark>, <mark>HTML</mark> y <mark>CSS</mark>.
  
  He trabajado también con <mark>Ionic</mark> y he usado <mark>BEM</mark> como patrón organizativo. 
  
  Estoy acostumbrada a trabajar con metodología ágiles, <mark>SCRUM</mark> y <mark>Kanban</mark>, utilizando <mark>Jira</mark> y <mark>Git-Flow</mark> para organizar tareas y código. 
  
  La revisión de código para mí es algo indispensable, y creo firmemente que una buena sesión de pair programming puede ser muy efectiva y rápida para solucionar problemas o bloqueos.

  También he trabajado en la parte de testing, con tests <mark>End-To-End</mark> y con <mark>Jest</mark>.
  
  
  
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: Boream
        caption: 1/2019 - 03/2019,
        sub_title: Web Develop Bootcamp (640 horas)
      - layout: center
        title: Universidad de Murcia
        caption: 1/2013 - 09/2013,
        sub_title: Máster Universitario en Nutrición y Seguridad Alimentaria.
      - layout: center
        title: Universidad de Cádiz
        caption: 9/2011 - 6/2012,
        sub_title: Máster Universitario en Acuicultura y Pesca: recursos marinos y sostenibilidad.
      - layout: center
        title: Universidad de Cádiz
        caption: 9/2004 - 6/2011,
        sub_title: Doble Licenciatura en Ciencias del Mar y Ciencias Ambientales.
      
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
